### ISSUE TITLE
Suggested URLs in the docs for using `<link>` includes return 404s

### ISSUE THREAD

**Issue by dslatkin** [bigskysoftware/missing#25]
On the [intro page](https://missing.style/docs/) for the docs, it suggests using the following to include the styles on a page:

```css
<link rel="stylesheet" href="https://the.missing.style/1.0.0/missing.min.css">
<!-- Prism theme (https://prismjs.com/): -->
<link rel="stylesheet" href="https://the.missing.style/1.0.0/missing-prism.min.css">
```

But visiting the links directly shows they're returning 404s:

- https://the.missing.style/1.0.0/missing.min.css
- https://the.missing.style/1.0.0/missing-prism.min.css

**Comment by Michael-J-Ward** [comment]
It'd be nice to include SRI integrity hash [like you do with htmx](https://github.com/bigskysoftware/htmx/issues/261). Alternatively, update cors header so that we can retrieve it ourself with https://www.srihash.org/
