### ISSUE TITLE
Caching differences with the.missing.style and unpkg

### ISSUE THREAD

**Issue by atamanroman** [bigskysoftware/missing#27]
I guess it's intended, but it looks like https://the.missing.style is not cached at all while unpkg of course is.

The instructions on GitHub and missing.style differ in the URL and it took me a few minutes to figure out that's the reason caching is not working.

Maybe a hint in README.md would suffice.

**Comment by dz4k** [comment]
I have edited the readme to remove the reference to `the.missing.style`. New projects should use unpkg or another NPM CDN, or ideally download the npm package and serve it from their own server. `the.` is only being maintained for compatibility.
