### ISSUE TITLE
The tabs demo on the website does not work properly

### ISSUE THREAD

**Issue by isaacvando** [bigskysoftware/missing#29]
When I click on the second or third tab the first tab stays open.

**Comment by fkscott** [comment]
I believe I have addressed this in my [pull request](https://github.com/bigskysoftware/missing/pull/38). Can you verify if this works for you @isaacvando ?

**Comment by isaacvando** [comment]
Nice! I haven't really used this library and am working on other things now so i will let someone else test it.

**Comment by dz4k** [comment]
this is fixed on the current website -- lmk if it's broken for anyone else and I'll reopen.
