### ISSUE TITLE
Hosted CSS URLs 404

### ISSUE THREAD

**Issue by MariusVolkhart** [bigskysoftware/missing#34]
Both `<link rel="stylesheet" href="https://unpkg.com/missing.css@1.1.0">` and `<link rel="stylesheet" href="https://the.missing.style">` result in a 404.

**Comment by MariusVolkhart** [comment]
The demos and playground pages of the website are broken as well at the moment

**Comment by j4mie** [comment]
The documentation is broken too (eg see [here](https://missing.style/docs/components/)), but I'm not sure if this the same issue. It looks like it could be that the HTML is malformed.

**Comment by juliojimenez** [comment]
When I go to https://the.missing.style in the browser, I expect to see a bunch of CSS, but I get this....

`Cannot find package missing.css@missing.css@1.1.1`

Where are y'all hosting this?

**Comment by dz4k** [comment]
Sorry for the late response.

The unpkg bug was fixed since 1.1.1.

I believe I've identified why the.missing.style is broken as well, but I'll need to fix some other things first.

**Comment by dz4k** [comment]
I've finally managed to fix this -- @juliojimenez @MariusVolkhart can you check that it works?

**Comment by dz4k** [comment]
(closing -- will reopen if issue continues)
