### ISSUE TITLE
403 when loading js from unpkg

### ISSUE THREAD

**Issue by mr55p-dev** [bigskysoftware/missing#41]
When I include the nav example `<script type="module" src="https://unpkg.com/missing.css@/js/overflow-nav.js"></script>` in my site the script is loaded, and visiting the URL in my browser gives `{"error":"Invalid URL: /missing.css@/js/overflow-nav.js"}`. Still works if I serve `19.js` and `overflow-nav.js` myself, but just thought I should flag it 😄

**Comment by dz4k** [comment]
Thanks for reporting. This was an issue in the docs -- the correct URL is `https://unpkg.com/missing.css@1.1.1/dist/js/overflow-nav.js` as is now shown.
