### ISSUE TITLE
Light / Dark theme cannot be switched by the user independently from system settings

### ISSUE THREAD

**Issue by giuliop** [bigskysoftware/missing#52]
It's great that missing.css ships with a dark theme, however the theme can only be switched by the OS system system-wide settings.
It would be nice if we could let the user switch the theme as well independently from the system settings.
Ideally we would simply apply an explicit `class="dark-theme"` to the html element or something similar.

**Comment by DavesBorges** [comment]
> It's great that missing.css ships with a dark theme, however the theme can only be switched by the OS system system-wide settings. It would be nice if we could let the user switch the theme as well independently from the system settings. Ideally we would simply apply an explicit `class="dark-theme"` to the html element or something similar.

@giuliop  You can achieve the same thing by adding a class "-no-dark-theme" to your root element [https://missing.style/docs/utils/#no-dark-theme](https://missing.style/docs/utils/#no-dark-theme)

Example:

```javascript
function toggleTheme(){
   if(document.documentElement.classList.contains("-no-dark-theme")){
       document.documentElement.classList.remove("-no-dark-theme");
       return;
   }
   document.documentElement.classList.add("-no-dark-theme");
}
```

**Comment by DavesBorges** [comment]
A more general solution would be:
Adding this to your css file (copied from the [variables.css](https://github.com/bigskysoftware/missing/blob/dev/src/variables.css))
```css

:root.dark-theme {
/* Colors */
    --fg: var(--gray-0);
    --muted-fg: var(--gray-2);
    --faded-fg: var(--gray-7);

    --plain-bg: var(--gray-11);
    --info-bg: var(--blue-12);
    --ok-bg: var(--green-12);
    --bad-bg: var(--red-12);
    --warn-bg: var(--yellow-12);

    --plain-faded-fg: var(--blue-6);
    --info-faded-fg: var(--blue-6);
    --ok-faded-fg: var(--green-6);
    --bad-faded-fg: var(--red-6);
    --warn-faded-fg: var(--yellow-6);

    --bg: var(--gray-12);
    --box-bg: var(--gray-10);
    --interactive-bg: var(--gray-8);

    --plain-fg: (--blue-2);
    --info-fg: var(--blue-2);
    --ok-fg: var(--green-2);
    --bad-fg: var(--red-2);
    --warn-fg: var(--yellow-2);

    --accent: var(--blue-2);
    --muted-accent: var(--blue-5);
}
```

And then the toggleTheme would look like:
```javascript
function toggleTheme(){
    if(document.documentElement.classList.contains("-no-dark-theme")){
	    // Enable darktheme
	    document.documentElement.classList.remove("-no-dark-theme");
	    document.documentElement.classList.add("dark-theme");
	    return;
    }
    // Enable black theme
    document.documentElement.classList.add("-no-dark-theme");
    document.documentElement.classList.remove("dark-theme");
}
```

**Comment by giuliop** [comment]
Thanks, this works very well !
I still think it would be a good idea to add the `dark-theme` class directly to missing.css to avoid pasting the `variable.css` css back in your custom css file, don't see any downside with that beside an insignificant size increase.

**Comment by DavesBorges** [comment]
If you still 

> Thanks, this works very well ! I still think it would be a good idea to add the `dark-theme` class directly to missing.css to avoid pasting the `variable.css` css back in your custom css file, don't see any downside with that beside an insignificant size increase.

Glad I was helpful. Please notice that I'm not a mantainer of the project. So if you'd like this feature to be implemented into the project, consider leaving the issue open so the mantainers can have a look at it and consider it.

**Comment by giuliop** [comment]
I thought you were the maintainer :)
Reopening them so they can give a look
