### ISSUE TITLE
Switch widget

### ISSUE THREAD

**Issue by dz4k** [bigskysoftware/missing#63]
Style `<input type=checkbox role=switch>` to be a toggle switch

**Comment by geoffrey-eisenbarth** [comment]
Are we trying to do anything drastically different from the markup in [the WAI example] (https://www.w3.org/WAI/ARIA/apg/patterns/switch/examples/switch-checkbox/) or is that a good starting place?

**Comment by dz4k** [comment]
We shouldn't need any more markup than `<input type=checkbox role=switch>` thanks to `appearance: none;` and pseudoelements

**Comment by geoffrey-eisenbarth** [comment]
I've put something together, but I recently saw [Adrian Roselli's take](https://adrianroselli.com/2019/03/under-engineered-toggles.html) and want to implement some of their considerations. Hoping to have a PR this week, but we'll see.

**Comment by geoffrey-eisenbarth** [comment]
Closed by #69
